version: '3'

services:

  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/apache-flask/app
      - type : bind
        source: ./data
        target: /var/www/apache-flask/data
        read_only: false
    restart: always
    container_name: web
