version: '3'

services:

  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/apache-flask/
    command: su -c "/usr/sbin/apache2ctl -D FOREGROUND"
    restart: always
    container_name: web

