version: '3'
services:
  
  sqlite3:
    image: sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./data/:/var/www/apache-flask/data/  
  
  web:
        build: .
        ports:
          - "80:80"
        volumes:
          - ./app:/var/www/apache-flask/app
        restart: always


